project:
  type: website

website:
  title: GeoPolitical Risk Analysis
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO-523-ManasPPanse/final-project-manasppanse
    left:
      - text: Project
        href: index.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true

execute:
  freeze: auto